### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by blank-track** [KangchengLiu/Feature-Geometric-Net-FG-Net#12]
Hi, this is a great project. Will you update the code of the pytorch version later？
look forward to your reply ：）

**Comment by KangchengLiu** [comment]
https://github.com/KangchengLiu/Feature-Geometric-Net-FG-Net/blob/main/Segmentation/requirements.txt

**Comment by blank-track** [comment]
Thank you for your reply！
It seems that the model _**ml3d.pipelines.SemanticSegmentation**_ is not found in the project
Can you share relevant codes ，thanks ：）
