### ISSUE TITLE
An instruction to run the code

### ISSUE THREAD

**Issue by umbrellait-maksim-titarenko** [KangchengLiu/Feature-Geometric-Net-FG-Net#8]
Hello!

Thanks for the repo, it looks like a great work.
However, I have troubles running the code.

Can you provide an instruction - how exactly to launch the training process?

**Comment by KangchengLiu** [comment]
Hi, the training code for each dataset is provided in the Train_Visualize folder. We merely can not realize the code of FG-Net as our code is used for an HK local project. FG-Net is a simple combination of geometric convolution and attention, you can simply reimplement it according to our paper.
